# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_sampleQC = QtWidgets.QLineEdit(self.centralwidget)
        self.le_sampleQC.setEnabled(True)
        self.le_sampleQC.setFocusPolicy(QtCore.Qt.NoFocus)
        self.le_sampleQC.setObjectName("le_sampleQC")
        self.verticalLayout_2.addWidget(self.le_sampleQC)
        self.le_midQC = QtWidgets.QLineEdit(self.centralwidget)
        self.le_midQC.setFocusPolicy(QtCore.Qt.NoFocus)
        self.le_midQC.setObjectName("le_midQC")
        self.verticalLayout_2.addWidget(self.le_midQC)
        self.le_pics_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.le_pics_dir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.le_pics_dir.setObjectName("le_pics_dir")
        self.verticalLayout_2.addWidget(self.le_pics_dir)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_sampleQC_open = QtWidgets.QPushButton(self.centralwidget)
        self.pb_sampleQC_open.setObjectName("pb_sampleQC_open")
        self.verticalLayout.addWidget(self.pb_sampleQC_open)
        self.pb_midQC_open = QtWidgets.QPushButton(self.centralwidget)
        self.pb_midQC_open.setObjectName("pb_midQC_open")
        self.verticalLayout.addWidget(self.pb_midQC_open)
        self.pb_pics_dir_open = QtWidgets.QPushButton(self.centralwidget)
        self.pb_pics_dir_open.setObjectName("pb_pics_dir_open")
        self.verticalLayout.addWidget(self.pb_pics_dir_open)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.pb_generation = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_generation.sizePolicy().hasHeightForWidth())
        self.pb_generation.setSizePolicy(sizePolicy)
        self.pb_generation.setFlat(False)
        self.pb_generation.setObjectName("pb_generation")
        self.horizontalLayout.addWidget(self.pb_generation)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.te_log = QtWidgets.QTextEdit(self.centralwidget)
        self.te_log.setObjectName("te_log")
        self.verticalLayout_3.addWidget(self.te_log)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 7)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 23))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QCReportTool"))
        self.pb_sampleQC_open.setText(_translate("MainWindow", "样本QC文件"))
        self.pb_midQC_open.setText(_translate("MainWindow", "中间QC文件"))
        self.pb_pics_dir_open.setText(_translate("MainWindow", "资源文件夹"))
        self.pb_generation.setText(_translate("MainWindow", "生成报告"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
